# frozen_string_literal: true

source %(https://rubygems.org)

group :development do
  %w[
    rake
    solargraph
  ].each do |pkg|
    gem pkg
  end
end

group :production do
  gem %(abstract-synthesizer)
  gem %(thor)
end
